version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run: pip install -U vim-vint
      - run: vint colors/
  build:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends vim-gtk3
      - run:
          name: Generate previews
          command: |
            mkdir -p dist
            ci/generate.sh gvim dark_gui
            ci/generate.sh gvim light_gui
            ci/generate.sh vim dark_256
            ci/generate.sh vim light_256
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    docker:
      - image: cimg/node:22.14
        environment:
          NPM_CONFIG_PREFIX: "~/.npm-global"
    steps:
      - checkout
      - run: echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - npm-{{ arch }}
      - run: npm install -g gh-pages
      - save_cache:
          key: npm-{{ arch }}
          paths:
            - ~/.npm
            - ~/.npm-global
      - attach_workspace:
          at: .
      - run: |
          git config user.name "$(git --no-pager show --no-patch --format='%an')"
          git config user.email "$(git --no-pager show --no-patch --format='%ae')"
      - add_ssh_keys:
          fingerprints:
            - "uQFw4yrd8TZKe6rsAFpqfc6wbNRLUk7C+2tb6jK8A4M"
      - run:
          command: gh-pages --branch gh-pages --dist dist --message "Update to ${CIRCLE_SHA1:0:7} [ci skip]"
          environment:
            CACHE_DIR: "~/.npm-global/.cache"

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
